version: '3'
services:
  db:
    image: bitnami/postgresql:9.5.3-r6
    ports:
      - '5433:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    env_file: .env
    restart: always

  feedsucker:
    build: .
    links: 
      - db
    depends_on: 
      - db
    env_file: .env
    tty: true
    stdin_open: true
    restart: always

